<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <AssemblyName>StarPie</AssemblyName>
    <Title>StarPie</Title>
    <Product>StarPie</Product>
    <Company>StarPie Studio</Company>
    <Description>StarPie - 现代化高颜值 Windows 鼠标轮盘笔势与效率管理系统</Description>
    <Version>1.4.1</Version>
    <AssemblyVersion>1.4.1.0</AssemblyVersion>
    <FileVersion>1.4.1.0</FileVersion>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\CSharp\StarPie\WinPieGestures\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\CSharp\StarPie\WinPieGestures\.editorconfig" />
  </ItemGroup>

</Project>
