global using StarPie.Host.Configuration;
global using StarPie.Host.Localization;
global using StarPie.Sdk.Models;
global using StarPie.Host.Ports;
global using StarPie.Sdk.Services.Messages;
global using StarPie.Sdk.Services.Wheel;
global using StarPie.Host.Themes;
global using StarPie.Sdk.ViewModels.Wheel;
global using StarPie.Host.Wheel;
